name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-run-test:
    name: Build, run, and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build svcs
        run: docker compose build
      - name: Run svcs
        run: docker compose up -d
      - name: watch svcs
        run: docker compose logs -f -t

#      - name: Wait for svcs
#        run: sleep 10
##        run: while [ $(curl -LI http://localhost:5000 -o /dev/null -w '%{http_code}\n' -s) != "200" ] ; do echo waiting... ; sleep 2 ; done
#      - name: Install requirements
#        run: pip3 install -r tests/requirements.txt
#      - name: Run tests
#        run: cd tests && python3 mlflow_test.py
#      - name: Clean up
#        run: docker compose down --volumes
