name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build svcs
        run: docker compose build
      - name: Run svcs
        run: docker compose up -d
  tests:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, 3.10]
    steps:
      - uses: actions/checkout@v3
      - name: Install requirements
        run: pip3 install -r tests/requirements.txt
      - name: Run tests
        run: cd tests && python3 mlflow_test.py
      - name: Clean up
        run: docker compose down --volumes
